name: "Generate README markdown table"

on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  readme-generator:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Prepare repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.ref }}

    - name: Prepare Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Run table generator
      run: | 
        cd .github/workflows/markdown-table-workflow
        npm install
        node index.js

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "docs: update README table"
